# pragma once

# define PACKAGE_DESCRIPTION_SUMMARY "@CPACK_PACKAGE_DESCRIPTION_SUMMARY@"
# define PACKAGE_VENDOR "@CPACK_PACKAGE_VENDOR@"
# define PACKAGE_FILE_NAME "@CPACK_PACKAGE_FILE_NAME@"
# define PACKAGE_EXECUTABLES "@CPACK_PACKAGE_EXECUTABLES@"
# define PACKAGE_NAME "@PROJECT_NAME@"

# define VERSION "@VERSION@"
# define VERSION_GROUPING_NAME @VERSION_GROUPING_NAME@
# define VERSION_MAJOR @VERSION_MAJOR@
# define VERSION_MINOR @VERSION_MINOR@
# define VERSION_PATCH @VERSION_PATCH@
# define VERSION_BUILD @VERSION_BUILD@
# define LAST_COMMIT_ID "@LAST_COMMIT_ID@"
# define GIT_VERSION "@GIT_VERSION@"
# define GIT_BRANCH "@GIT_BRANCH@"

# define CMAKE_BUILD_TYPE "@CMAKE_BUILD_TYPE@"
# define CMAKE_SYSTEM "@CMAKE_SYSTEM@"
# define CMAKE_SYSTEM_NAME "@CMAKE_SYSTEM_NAME@"
# define CMAKE_SYSTEM_PROCESSOR "@CMAKE_SYSTEM_PROCESSOR@"

# define CMAKE_BINARY_DIR "@CMAKE_BINARY_DIR@"
# define CMAKE_SOURCE_DIR "@CMAKE_SOURCE_DIR@"

# define messageconv_BINARY_DIR "@messageconv_BINARY_DIR@"
# define messageconv_SOURCE_DIR "@messageconv_SOURCE_DIR@"

# define EXECUTABLE_NAME "@EXECUTABLE_NAME@"
# define PKG_SUBNAME "@PKG_SUBNAME@"
# define BINARY_BIT @BINARY_BIT@
# define NAME_SUFFIXES "@NAME_SUFFIXES@"

# define CMAKE_C_COMPILER_ID "@CMAKE_C_COMPILER_ID@"
# define CMAKE_C_COMPILER_VERSION "@CMAKE_C_COMPILER_VERSION@"
# define CMAKE_C_FLAGS "@CMAKE_C_FLAGS@"
# define CMAKE_CXX_COMPILER_ID "@CMAKE_CXX_COMPILER_ID@"
# define CMAKE_CXX_COMPILER_VERSION "@CMAKE_CXX_COMPILER_VERSION@"
# define CMAKE_CXX_FLAGS "@CMAKE_CXX_FLAGS@"

# define OPENSSL_VERSION_STR "@OPENSSL_VERSION@"
# define Boost_VERSION "@Boost_VERSION@"
# define Boost_LIB_VERSION "@Boost_LIB_VERSION@"
# define GIT_VERSION "@GIT_VERSION@"

# define LOG_ACTIVE_LEVEL @LOG_ACTIVE_LEVEL@
# cmakedefine USE_BACKWARD
# cmakedefine MARIADBCLIENT_FOUND
# cmakedefine SQLITE3_FOUND
# cmakedefine JSONCPP_FOUND

# ifndef SOURCE_PATH_SIZE
# define SOURCE_PATH_SIZE @SOURCE_PATH_SIZE@
# endif
